name: Build all labs>2

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run lab3 Action
        uses: ./liu_732A94/lab3/.github/workflows/my-action.yml
